# Generated by Django 3.2 on 2021-06-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbase',
            old_name='address',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='userbase',
            old_name='city',
            new_name='address_line_2',
        ),
        migrations.RenameField(
            model_name='userbase',
            old_name='post_code',
            new_name='town_city',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='last_name',
        ),
        migrations.AddField(
            model_name='userbase',
            name='postcode',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
